# **Graphs**

|1|2|3|
|-|-|-|
|4|5|6|
|7|B|8|

In [47]:
n = 6 # number of nodes
e = 7 # number of edges

edges = [(0,1),(0,3),(0,4),(1,2),(1,5),(2,4),(3,4)]  # edges

In [61]:
adjList = []
for i in range(n):
    adjList.append([])
for edge in edges:
    x = edge[0]
    y = edge[1]

    adjList[x].append(y)
    adjList[y].append(x)
    
for i in range(n):
    print(i, "-->", adjList[i])
    
    

0 --> [1, 3, 4]
1 --> [0, 2, 5]
2 --> [1, 4]
3 --> [0, 4]
4 --> [0, 2, 3]
5 --> [1]


In [49]:
n = 6 # number of nodes
e = 7 # number of edges
adjMatrix = []
edges = [(0,1),(0,3),(0,4),(1,2),(1,5),(2,4),(3,4)]  # edges

for i in range(n):
    list1 = [-1]*n
    adjMatrix.append(list1)
    
for x,y in edges:
    adjMatrix[x][y] = 1
    adjMatrix[y][x] = 1
    
for i in adjMatrix:
    print(i)

[-1, 1, -1, 1, 1, -1]
[1, -1, 1, -1, -1, 1]
[-1, 1, -1, -1, 1, -1]
[1, -1, -1, -1, 1, -1]
[1, -1, 1, 1, -1, -1]
[-1, 1, -1, -1, -1, -1]


In [50]:
#Adjacency Matrix form of the graph

import numpy as np

AMat = np.zeros(shape = (6, 6))            #Initialize the Adjacency Matrix with all zero element
print("All-Zero Adjacency Matrix :\n")
print(AMat)

All-Zero Adjacency Matrix :

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [51]:
for(i,j) in edges:
    AMat[i,j] = 1                 #Populate the Adjacency Matrix with 1 where the edges are connected
    AMat[j,i] = 1

print("Populated Adjacency Matrix :\n")
print(AMat)

Populated Adjacency Matrix :

[[0. 1. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


### **BFS Traversal**

In [86]:
start = 0
visited = {start}
queue = [start]
ans = [start]

while queue:
    for i in adjList[queue.pop(0)]:
        if i not in visited:
            queue.append(i)
            visited.add(i)
            ans.append(i)
            
print(ans)

[0, 1, 3, 4, 2, 5]


In [65]:
def BFS(adjList, start):
    visited = {start}
    queue = [start]
    ans = [start]

    while queue:
        front = queue.pop(0)
        for i in adjList[front]:
            if i not in visited:
                queue.append(i)
                visited.add(i)
                ans.append(i)
    return ans

In [67]:
print(BFS(adjList, 0))

[0, 1, 3, 4, 2, 5]


In [126]:
def DFS(adjList, start):
    visited = set()
    stack = [start]
    ans = []

    while stack:
        end = stack.pop()
        if end not in visited:
            ans.append(end)
            visited.add(end)
            for i in adjList[end]:
                if i not in visited:
                    stack.append(i)
    return ans

In [127]:
print(DFS(adjList, 0))

[0, 4, 3, 2, 1, 5]


In [ ]:
# Iterative DFS (using a stack)
def dfs(graph, start):
    visited = set()
    stack = [start]
    ans = []
    while stack:
        node = stack.pop()
        if node not in visited:
            visited.add(node)
            ans.append(node)
            for neighbor in reversed(graph[node]):
                if neighbor not in visited:
                    stack.append(neighbor)
    return ans

In [115]:
print(dfs(adjList, 0))

[0, 1, 2, 4, 3, 5]
