# NumPy — Complete Notes & Practice Notebook

A practical, beginner-to-advanced reference for **NumPy (Numerical Python)**.


## 1. Installation and Import

If NumPy is not installed:

```bash
pip install numpy
```

Then import it using the conventional alias `np`.

In [151]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.2.6


## 2. What is NumPy?

NumPy provides the `ndarray`, an efficient multidimensional array object, plus functions for numerical computing.

Compared with ordinary Python lists, NumPy arrays support fast **vectorized operations**, convenient multidimensional indexing, broadcasting, statistics, and linear algebra.

### Key idea

- **Array** = collection of values
- **Dimension / axis** = direction along which an array is organized
- **Shape** = size along each axis
- **dtype** = type of each array element
- **size** = total number of elements

In [152]:
# Python list
python_list = [1, 2, 3, 4]

# NumPy array
numpy_array = np.array([1, 2, 3, 4])

print(python_list)
print(numpy_array)
print(type(numpy_array))

[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>


## 3. Creating Arrays

In [153]:
# 1D array
a = np.array([10, 20, 30, 40])

# 2D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3D array
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

print("1D:", a)
print("2D:\n", b)
print("3D:\n", c)

1D: [10 20 30 40]
2D:
 [[1 2 3]
 [4 5 6]]
3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### `ndim`, `shape`, `size`, `dtype`, `itemsize`, `nbytes`

In [154]:
arr = np.array([[10, 20, 30],
                  [40, 50, 60]])

print("ndim   :", arr.ndim)
print("shape  :", arr.shape)
print("size   :", arr.size)
print("dtype  :", arr.dtype)
print("itemsize:", arr.itemsize, "bytes")
print("nbytes :", arr.nbytes, "bytes")

ndim   : 2
shape  : (2, 3)
size   : 6
dtype  : int64
itemsize: 8 bytes
nbytes : 48 bytes


## 4. Data Types (`dtype`)

Common NumPy dtypes include:

- `int8`, `int16`, `int32`, `int64`
- `uint8`, `uint16`, ...
- `float16`, `float32`, `float64`
- `complex64`, `complex128`
- `bool`
- strings/object types

Use `dtype=` when you need a specific type.

In [155]:
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1, 2, 3], dtype=np.float64)
c = np.array([True, False, True], dtype=bool)

print(a, a.dtype)
print(b, b.dtype)
print(c, c.dtype)

# Convert dtype
d = a.astype(np.float64)
print(d, d.dtype)

[1 2 3] int32
[1. 2. 3.] float64
[ True False  True] bool
[1. 2. 3.] float64


## 5. Array Creation Functions

In [156]:
print("zeros:", np.zeros(5))
print("ones :", np.ones(5))
print("full :", np.full(5, 7))
print("empty:", np.empty(5))  # values are uninitialized

print("\n2D zeros:\n", np.zeros((2, 3)))
print("\nIdentity matrix:\n", np.eye(3))

zeros: [0. 0. 0. 0. 0.]
ones : [1. 1. 1. 1. 1.]
full : [7 7 7 7 7]
empty: [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]

2D zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### `arange()` and `linspace()`

In [157]:
print("arange:", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 10, 5))

# Geometric spacing
print("logspace:", np.logspace(0, 3, 4))

arange: [0 2 4 6 8]
linspace: [ 0.   2.5  5.   7.5 10. ]
logspace: [   1.   10.  100. 1000.]


### Array creation from existing arrays

In [158]:
x = np.array([1, 2, 3])

print("zeros_like :", np.zeros_like(x))
print("ones_like  :", np.ones_like(x))
print("full_like  :", np.full_like(x, 9))

zeros_like : [0 0 0]
ones_like  : [1 1 1]
full_like  : [9 9 9]


## 6. Indexing

In [159]:
arr = np.array([10, 20, 30, 40, 50])

print("First:", arr[0])
print("Third:", arr[2])
print("Last:", arr[-1])

matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

print("50:", matrix[1, 1])
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])

First: 10
Third: 30
Last: 50
50: 50
First row: [10 20 30]
Second column: [20 50]


## 7. Slicing

Syntax:

```python
array[start:stop:step]
```

The `stop` index is excluded.

In [160]:
arr = np.array([0, 10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])
print(arr[::-1])

matrix = np.arange(1, 13).reshape(3, 4)
print("\nMatrix:\n", matrix)
print("\nRows 0:2, columns 1:3:\n", matrix[0:2, 1:3])

[10 20 30]
[ 0 10 20]
[30 40 50]
[ 0 20 40]
[50 40 30 20 10  0]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Rows 0:2, columns 1:3:
 [[2 3]
 [6 7]]


## 8. Boolean Indexing and Fancy Indexing

In [161]:
arr = np.array([10, 15, 20, 25, 30, 35])

mask = arr > 20
print("Mask:", mask)
print("Values > 20:", arr[mask])

# Multiple conditions
print("Between 15 and 30:", arr[(arr >= 15) & (arr <= 30)])

# Fancy indexing
indices = [0, 2, 5]
print("Selected indices:", arr[indices])

Mask: [False False False  True  True  True]
Values > 20: [25 30 35]
Between 15 and 30: [15 20 25 30]
Selected indices: [10 20 35]


## 9. Reshaping

The number of elements must remain unchanged.

In [162]:
arr = np.arange(1, 13)

matrix = arr.reshape(3, 4)
print(matrix)

# Let NumPy infer one dimension
print("\n2 x inferred:\n", arr.reshape(2, -1))

# Flatten
print("\nflatten:", matrix.flatten())

# Ravel
print("ravel:", matrix.ravel())

# Transpose
print("\ntranspose:\n", matrix.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2 x inferred:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### `resize()` vs `reshape()`

- `reshape()` returns an array with a new shape and preserves the number of elements.
- `resize()` can change the total number of elements and may modify the original array.

In [163]:
a = np.arange(6)
print("reshape:", a.reshape(2, 3))

b = np.arange(6)
b.resize(2, 4)
print("resize:", b)

reshape: [[0 1 2]
 [3 4 5]]
resize: [[0 1 2 3]
 [4 5 0 0]]


## 10. Copy vs View

A **view** shares the underlying data; a **copy** has independent data.

This distinction matters when slicing arrays.

In [164]:
original = np.array([1, 2, 3, 4])

view = original[1:3]
view[0] = 99

print("After changing view:")
print("original:", original)
print("view    :", view)

original = np.array([1, 2, 3, 4])
copy = original[1:3].copy()
copy[0] = 99

print("\nAfter changing copy:")
print("original:", original)
print("copy    :", copy)

After changing view:
original: [ 1 99  3  4]
view    : [99  3]

After changing copy:
original: [1 2 3 4]
copy    : [99  3]


## 11. Joining Arrays

In [165]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate((a, b)))
print("hstack     :", np.hstack((a, b)))
print("vstack     :\n", np.vstack((a, b)))

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("\nConcatenate axis=0:\n", np.concatenate((A, B), axis=0))
print("\nConcatenate axis=1:\n", np.concatenate((A, B), axis=1))

concatenate: [1 2 3 4 5 6]
hstack     : [1 2 3 4 5 6]
vstack     :
 [[1 2 3]
 [4 5 6]]

Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


## 12. Splitting Arrays

In [166]:
arr = np.arange(1, 10)

print("split:", np.split(arr, 3))
print("array_split:", np.array_split(arr, 4))

matrix = np.arange(1, 13).reshape(3, 4)
print("\nVertical split:\n", np.vsplit(matrix, 3))
print("\nHorizontal split:\n", np.hsplit(matrix, 2))

split: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
array_split: [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

Vertical split:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

Horizontal split:
 [array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


## 13. Broadcasting

Broadcasting lets NumPy operate on arrays with compatible shapes without manually copying values.

Example: a scalar is broadcast across every element.

In [167]:
arr = np.array([1, 2, 3])
print(arr + 10)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row = np.array([10, 20, 30])

print("\nRow broadcasting:\n", matrix + row)

column = np.array([[10],
                   [20]])
print("\nColumn broadcasting:\n", matrix + column)

[11 12 13]

Row broadcasting:
 [[11 22 33]
 [14 25 36]]

Column broadcasting:
 [[11 12 13]
 [24 25 26]]


### Broadcasting rule

Compare shapes from **right to left**. Two dimensions are compatible when:

1. They are equal, or
2. One of them is `1`, or
3. One of the dimensions does not exist.

Otherwise NumPy raises a broadcasting error.

In [168]:
# Compatible shapes: (2, 3) and (3,)
A = np.ones((2, 3))
B = np.array([10, 20, 30])
print(A + B)

# Compatible shapes: (2, 3) and (2, 1)
C = np.array([[10], [20]])
print("\n", A + C)

[[11. 21. 31.]
 [11. 21. 31.]]

 [[11. 11. 11.]
 [21. 21. 21.]]


## 14. Arithmetic Operations

In [169]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a // b:", a // b)
print("a % b:", a % b)
print("a ** 2:", a ** 2)

print("2 ** a:", 2 ** a)

a + b: [12 24 35]
a - b: [ 8 16 25]
a * b: [ 20  80 150]
a / b: [5. 5. 6.]
a // b: [5 5 6]
a % b: [0 0 0]
a ** 2: [100 400 900]
2 ** a: [      1024    1048576 1073741824]


### Universal Functions (ufuncs)

NumPy provides element-wise mathematical functions such as `sqrt`, `exp`, `log`, `sin`, `cos`, `abs`, `round`, `floor`, and `ceil`.

In [170]:
x = np.array([1, 4, 9, 16], dtype=float)

print("sqrt :", np.sqrt(x))
print("exp  :", np.exp([0, 1, 2]))
print("log  :", np.log([1, np.e, np.e**2]))
print("abs  :", np.abs([-3, -1, 2]))
print("floor:", np.floor([1.2, 2.9, -1.2]))
print("ceil :", np.ceil([1.2, 2.1, -1.2]))
print("round:", np.round([1.234, 2.678], 2))

sqrt : [1. 2. 3. 4.]
exp  : [1.         2.71828183 7.3890561 ]
log  : [0. 1. 2.]
abs  : [3 1 2]
floor: [ 1.  2. -2.]
ceil : [ 2.  3. -1.]
round: [1.23 2.68]


## 15. Comparisons and Logical Operations

In [171]:
a = np.array([1, 2, 3, 4, 5])

print(a > 3)
print(a == 3)
print(a != 3)

condition = (a > 1) & (a < 5)
print("1 < a < 5:", condition)
print("Selected:", a[condition])

print("any > 4:", np.any(a > 4))
print("all > 0:", np.all(a > 0))

[False False False  True  True]
[False False  True False False]
[ True  True False  True  True]
1 < a < 5: [False  True  True  True False]
Selected: [2 3 4]
any > 4: True
all > 0: True


### `where()`, `select()`, `clip()`

In [172]:
a = np.array([10, 20, 30, 40, 50])

print("Indices > 25:", np.where(a > 25))
print("Replace values:", np.where(a >= 30, 1, 0))

print("clip 20..40:", np.clip(a, 20, 40))

# Piecewise selection
conditions = [a < 20, a < 40]
choices = ["low", "medium"]
print("select:", np.select(conditions, choices, default="high"))

Indices > 25: (array([2, 3, 4]),)
Replace values: [0 0 1 1 1]
clip 20..40: [20 20 30 40 40]
select: ['low' 'medium' 'medium' 'high' 'high']


## 16. Aggregation and Statistics

In [173]:
data = np.array([10, 20, 30, 40, 50])

print("sum     :", np.sum(data))
print("mean    :", np.mean(data))
print("median  :", np.median(data))
print("min     :", np.min(data))
print("max     :", np.max(data))
print("std     :", np.std(data))
print("variance:", np.var(data))
print("percentile 50:", np.percentile(data, 50))
print("percentile 90:", np.percentile(data, 90))

sum     : 150
mean    : 30.0
median  : 30.0
min     : 10
max     : 50
std     : 14.142135623730951
variance: 200.0
percentile 50: 30.0
percentile 90: 46.0


### Aggregation along an axis

In [174]:
data = np.array([[10, 20, 30],
                   [40, 50, 60]])

print("Sum of all:", np.sum(data))
print("axis=0 (column-wise):", np.sum(data, axis=0))
print("axis=1 (row-wise):", np.sum(data, axis=1))

print("Mean axis=0:", np.mean(data, axis=0))
print("Mean axis=1:", np.mean(data, axis=1))

Sum of all: 210
axis=0 (column-wise): [50 70 90]
axis=1 (row-wise): [ 60 150]
Mean axis=0: [25. 35. 45.]
Mean axis=1: [20. 50.]


### Cumulative operations

In [175]:
a = np.array([1, 2, 3, 4])

print("cumsum:", np.cumsum(a))
print("cumprod:", np.cumprod(a))

cumsum: [ 1  3  6 10]
cumprod: [ 1  2  6 24]


## 17. Sorting and Searching

In [176]:
a = np.array([50, 10, 40, 20, 30])

print("sorted:", np.sort(a))
print("argsort:", np.argsort(a))

# Search positions
print("where a > 25:", np.where(a > 25))

# Insert/search in a sorted array
sorted_a = np.sort(a)
print("searchsorted:", np.searchsorted(sorted_a, [15, 35]))

sorted: [10 20 30 40 50]
argsort: [1 3 4 2 0]
where a > 25: (array([0, 2, 4]),)
searchsorted: [1 3]


### Unique values and counts

In [177]:
a = np.array([1, 2, 2, 3, 3, 3, 4])

print("unique:", np.unique(a))
print("unique with counts:", np.unique(a, return_counts=True))

values, counts = np.unique(a, return_counts=True)
print("Most frequent value:", values[np.argmax(counts)])

unique: [1 2 3 4]
unique with counts: (array([1, 2, 3, 4]), array([1, 2, 3, 1]))
Most frequent value: 3


## 18. Random Numbers

For reproducible experiments, use a random generator with a seed.

In [178]:
rng = np.random.default_rng(42)

print("Random floats:", rng.random(5))
print("Random integers:", rng.integers(1, 10, size=5))
print("Normal distribution:", rng.normal(loc=0, scale=1, size=5))
print("Uniform distribution:", rng.uniform(0, 1, size=5))

Random floats: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Random integers: [5 9 7 7 7]
Normal distribution: [-0.01680116 -0.85304393  0.87939797  0.77779194  0.0660307 ]
Uniform distribution: [0.82276161 0.4434142  0.22723872 0.55458479 0.06381726]


### Random arrays and sampling

In [179]:
rng = np.random.default_rng(42)

print(rng.integers(0, 100, size=(3, 4)))

values = np.array(["Python", "NumPy", "Pandas", "ML"])
print("Choice:", rng.choice(values, size=3, replace=True))
print("Permutation:", rng.permutation(values))

[[ 8 77 65 43]
 [43 85  8 69]
 [20  9 52 97]]
Choice: ['Pandas' 'ML' 'Pandas']
Permutation: ['NumPy' 'Python' 'Pandas' 'ML']


## 19. Linear Algebra

NumPy can perform vector and matrix operations.

### Dot product

In [180]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("dot product:", np.dot(a, b))
print("dot product with @:", a @ b)

dot product: 32
dot product with @: 32


### Matrix multiplication

In [181]:
A = np.array([[1, 2],
                [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A @ B:\n", A @ B)
print("matmul:\n", np.matmul(A, B))

A @ B:
 [[19 22]
 [43 50]]
matmul:
 [[19 22]
 [43 50]]


### Determinant, inverse, eigenvalues

In [182]:
A = np.array([[1., 2.],
                [3., 4.]])

print("determinant:", np.linalg.det(A))
print("inverse:\n", np.linalg.inv(A))
print("eigenvalues:", np.linalg.eigvals(A))

determinant: -2.0000000000000004
inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
eigenvalues: [-0.37228132  5.37228132]


### Solving linear equations

For `Ax = b`, prefer `np.linalg.solve(A, b)` instead of explicitly computing `A⁻¹`.

In [183]:
A = np.array([[3., 1.],
                [1., 2.]])
b = np.array([9., 8.])

x = np.linalg.solve(A, b)

print("Solution:", x)
print("Check A @ x:", A @ x)

Solution: [2. 3.]
Check A @ x: [9. 8.]


### Norms and matrix properties

In [184]:
A = np.array([[1., 2.],
                [3., 4.]])

print("Frobenius norm:", np.linalg.norm(A))
print("Rank:", np.linalg.matrix_rank(A))
print("Trace:", np.trace(A))

Frobenius norm: 5.477225575051661
Rank: 2
Trace: 5.0


## 20. Set Operations

In [185]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("union:", np.union1d(a, b))
print("intersection:", np.intersect1d(a, b))
print("difference a-b:", np.setdiff1d(a, b))
print("difference b-a:", np.setdiff1d(b, a))
print("symmetric difference:", np.setxor1d(a, b))
print("in b:", np.isin(a, b))

union: [1 2 3 4 5 6]
intersection: [3 4]
difference a-b: [1 2]
difference b-a: [5 6]
symmetric difference: [1 2 5 6]
in b: [False False  True  True]


## 21. Special Values: NaN and Infinity

In [186]:
a = np.array([1.0, np.nan, 3.0, np.inf, -np.inf])

print("isnan :", np.isnan(a))
print("isinf :", np.isinf(a))
print("isfinite:", np.isfinite(a))

print("sum:", np.sum(a))
print("nan-aware sum:", np.nansum(a))
print("nan-aware mean:", np.nanmean(a))

isnan : [False  True False False False]
isinf : [False False False  True  True]
isfinite: [ True False  True False False]
sum: nan
nan-aware sum: nan
nan-aware mean: nan


## 22. Handling Numerical Errors

In [187]:
# Example: divide by zero
with np.errstate(divide="ignore", invalid="ignore"):
    result = np.array([1.0, 0.0]) / np.array([0.0, 0.0])

print(result)

[inf nan]


## 23. Dates and Times

In [188]:
dates = np.array(["2026-01-01", "2026-01-02", "2026-01-03"], dtype="datetime64")

print(dates)
print("Difference:", dates[2] - dates[0])

days = np.arange("2026-01-01", "2026-01-06", dtype="datetime64[D]")
print(days)

['2026-01-01' '2026-01-02' '2026-01-03']
Difference: 2 days
['2026-01-01' '2026-01-02' '2026-01-03' '2026-01-04' '2026-01-05']


## 24. Vectorization

Vectorization means performing operations on whole arrays instead of writing Python loops element by element.

In [189]:
# Vectorized approach
x = np.arange(1_000_000)
y = x * 2 + 5

print(y[:10])

[ 5  7  9 11 13 15 17 19 21 23]


### Why vectorization matters

NumPy performs many operations using optimized low-level implementations. This usually makes numerical code faster and cleaner than equivalent Python loops.

The exact speedup depends on the operation, hardware, array size, and implementation.

In [190]:
# Same mathematical task using a loop
values = np.arange(10)

loop_result = [x * 2 + 5 for x in values]
numpy_result = values * 2 + 5

print("Loop :", loop_result)
print("NumPy:", numpy_result)

Loop : [np.int64(5), np.int64(7), np.int64(9), np.int64(11), np.int64(13), np.int64(15), np.int64(17), np.int64(19), np.int64(21), np.int64(23)]
NumPy: [ 5  7  9 11 13 15 17 19 21 23]


## 25. Common Array Manipulation Functions

In [191]:
a = np.arange(1, 7)

print("reshape:", a.reshape(2, 3))
print("transpose:", a.reshape(2, 3).T)
print("flatten:", a.reshape(2, 3).flatten())
print("ravel:", a.reshape(2, 3).ravel())
print("repeat:", np.repeat([1, 2, 3], 2))
print("tile:", np.tile([1, 2, 3], 2))

reshape: [[1 2 3]
 [4 5 6]]
transpose: [[1 4]
 [2 5]
 [3 6]]
flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]
repeat: [1 1 2 2 3 3]
tile: [1 2 3 1 2 3]


## 26. `meshgrid()`

`meshgrid()` is useful for creating coordinate grids, especially in mathematics, visualization, and machine learning.

In [192]:
x = np.array([1, 2, 3])
y = np.array([10, 20])

X, Y = np.meshgrid(x, y)

print("X:\n", X)
print("Y:\n", Y)

X:
 [[1 2 3]
 [1 2 3]]
Y:
 [[10 10 10]
 [20 20 20]]


## 27. Structured Arrays

Structured arrays allow different fields/dtypes in one NumPy array. For most tabular data analysis, Pandas is usually easier.

In [193]:
dtype = np.dtype([
    ("name", "U10"),
    ("age", "i4"),
    ("score", "f4")
])

students = np.array([
    ("Aman", 20, 85.5),
    ("Riya", 21, 91.0),
    ("Raj", 19, 78.5)
], dtype=dtype)

print(students)
print("Names:", students["name"])
print("Scores:", students["score"])

[('Aman', 20, 85.5) ('Riya', 21, 91. ) ('Raj', 19, 78.5)]
Names: ['Aman' 'Riya' 'Raj']
Scores: [85.5 91.  78.5]


## 28. Broadcasting + Linear Algebra Example

A simple feature-standardization example:

$$z = \frac{x - \mu}{\sigma}$$

This pattern appears frequently in Data Science and Machine Learning.

In [194]:
X = np.array([
    [10., 100.],
    [20., 200.],
    [30., 300.],
    [40., 400.]
])

mean = X.mean(axis=0)
std = X.std(axis=0)

Z = (X - mean) / std

print("Mean:", mean)
print("Std :", std)
print("Standardized data:\n", Z)

Mean: [ 25. 250.]
Std : [ 11.18033989 111.80339887]
Standardized data:
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


## 29. Practical Data-Science Patterns

In [195]:
# Find missing values
data = np.array([10., 20., np.nan, 40., np.nan])

print("Missing mask:", np.isnan(data))
print("Number missing:", np.isnan(data).sum())

# Replace NaN with mean
mean_value = np.nanmean(data)
filled = np.where(np.isnan(data), mean_value, data)

print("Filled:", filled)

Missing mask: [False False  True False  True]
Number missing: 2
Filled: [10.         20.         23.33333333 40.         23.33333333]


### Row/column filtering

In [196]:
X = np.array([
    [1, 10],
    [2, 20],
    [3, 30],
    [4, 40]
])

# Keep rows where first column > 2
filtered = X[X[:, 0] > 2]

print(filtered)

[[ 3 30]
 [ 4 40]]


In [197]:
# Exercise area
# Write your solutions below.

# 1.
# arr = ...

# 2.
# print(...)

# Continue with your own solutions.

# 30. Mini Project — Student Marks Analysis

Use NumPy to analyze this dataset.

Tasks:
1. Calculate each student's average.
2. Calculate subject-wise averages.
3. Find the highest total score.
4. Find the student with the highest average.
5. Find students whose average is at least 80.
6. Calculate standard deviation for each subject.
7. Normalize the marks between 0 and 1.

In [198]:
students = np.array(["Aman", "Riya", "Raj", "Priya", "Karan"])

marks = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [70, 75, 80],
    [88, 91, 84],
    [60, 72, 68]
], dtype=float)

subjects = np.array(["Python", "Math", "Statistics"])

# 1. Student averages
student_avg = marks.mean(axis=1)

# 2. Subject averages
subject_avg = marks.mean(axis=0)

# 3. Total scores
totals = marks.sum(axis=1)

# 4. Highest-average student
best_index = np.argmax(student_avg)

# 5. Students with average >= 80
high_performers = students[student_avg >= 80]

# 6. Subject standard deviations
subject_std = marks.std(axis=0)

# 7. Min-max normalization
min_values = marks.min(axis=0)
max_values = marks.max(axis=0)
normalized = (marks - min_values) / (max_values - min_values)

print("Student averages:", student_avg)
print("Subject averages:", subject_avg)
print("Totals:", totals)
print("Best student:", students[best_index])
print("Average of best student:", student_avg[best_index])
print("High performers:", high_performers)
print("Subject std:", subject_std)
print("Normalized marks:\n", normalized)

Student averages: [84.33333333 91.66666667 75.         87.66666667 66.66666667]
Subject averages: [79.  83.2 81. ]
Totals: [253. 275. 225. 263. 200.]
Best student: Riya
Average of best student: 91.66666666666667
High performers: ['Aman' 'Riya' 'Priya']
Subject std: [12.0664825   8.03492377  8.76356092]
Normalized marks:
 [[0.78125    0.94736842 0.37037037]
 [1.         0.84210526 1.        ]
 [0.3125     0.15789474 0.44444444]
 [0.875      1.         0.59259259]
 [0.         0.         0.        ]]
